{
 "title": "bad-chess",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Responses Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(responses_sent_total{job=\"bad-chess\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Go Routines",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "go_goroutines{job=\"bad-chess\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"bad-chess\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Manager Clients",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "manager_clients_current{job=\"bad-chess\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Current Matches",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "manager_matches_current{job=\"bad-chess\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Manager Clients and Matches",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "rate(manager_clients_total{job=\"bad-chess\"}[5m])",
     "legendFormat": "Connected Clients"
    },
    {
     "expr": "rate(manager_matches_total{job=\"bad-chess\"}[5m])",
     "legendFormat": "Matches"
    }
   ]
  },
  {
   "title": "Requests By Requester",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "requests_by_requester_total{job=\"bad-chess\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "requests received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "rate(requests_received_total{job=\"bad-chess\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Responses By Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "rate(responses_sent_by_status_total{job=\"bad-chess\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}