{
 "title": "Logs",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "fail2ban logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{filename=~\"/var/log/fail2ban.log\"} |= ``"
    }
   ]
  },
  {
   "title": "Caddy logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{filename=~\"/var/log/caddy/access.*\"} |= ``"
    }
   ]
  },
  {
   "title": "bad-chess logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=~\"bad-chess\"} |= ``"
    }
   ]
  }
 ]
}