---
- name: Install Grafana, Prometheus, Loki
  hosts: all
  gather_facts: no
  become: yes
  vars:
    ansible_user: bad-chess
    ansible_port: 65332
    webserver_port: 8080
    grafana_dashboard_provisioning_directory: /var/lib/grafana/dashboards
  tasks:
    - name: Add the Grafana GPG key
      ansible.builtin.apt_key:
        url: https://apt.grafana.com/gpg.key
        keyring: /etc/apt/keyrings/grafana.gpg
        state: present

    - name: Add the Grafana repository
      ansible.builtin.apt_repository:
        filename: grafana.list
        repo: "deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com stable main"
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Grafana
      apt:
        name: grafana
        state: present

    - name: Install Prometheus
      apt:
        name: prometheus
        state: present

    - name: Install Loki
      apt:
        name: loki
        state: present

    - name: Copy template datasources.yml for Grafana
      template:
        src: datasources.yml.j2
        dest: /etc/grafana/provisioning/datasources/datasources.yml

    - name: Copy template dashboards.yml for Grafana
      template:
        src: dashboards.yml.j2
        dest: /etc/grafana/provisioning/dashboards/dashboards.yml

    - name: Create dashboard directory if it does not exist
      ansible.builtin.file:
        path: "{{ grafana_dashboard_provisioning_directory }}"
        state: directory
        mode: '0755'

    - name: Copy bad-chess json dashboard
      ansible.builtin.copy:
        src: ./files/grafana-bad-chess.json
        dest: "{{ grafana_dashboard_provisioning_directory }}/grafana-bad-chess.json"

    - name: Enable and start Grafana service
      systemd:
        name: grafana-server
        enabled: yes
        state: restarted

    - name: Verify Grafana is running
      command: systemctl status grafana-server
      register: grafana_status
      changed_when: false
      failed_when: grafana_status.rc != 0

    - name: Copy template prometheus.yml for Prometheus
      template:
        src: prometheus.yml.j2
        dest: /etc/prometheus/prometheus.yml
      
    - name: Enable and start Prometheus service
      systemd:
        name: prometheus
        enabled: yes
        state: restarted

    - name: Verify Prometheus is running
      command: systemctl status prometheus
      register: prometheus_status
      changed_when: false
      failed_when: prometheus_status.rc != 0

    - name: Verify Loki is running
      command: systemctl status loki
      register: loki_status
      changed_when: false
      failed_when: loki_status.rc != 0
  