name: Build Release
on:
  pull_request:
    branches: 
      - main
    types: [closed]

jobs:
  build-release:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v ./...

